spring:
  application:
    name: workload-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: workloaddb
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}
    pool:
      enabled: true
      max-connections: 10

jwt:
  secret: ${JWT_KEY}

springdoc:
  swagger-ui:
    url: /workload-api.yaml
    path: /swagger-ui.html

server:
  port: 8085

jms:
  request-timeout-ms: 5000
  queues:
    trainer-workload: trainer.workload.queue
    trainer-workload-dlq: ActiveMQ.DLQ

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}