spring:
  datasource:
    url: jdbc:h2:mem:workloaddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}
    pool:
      enabled: true
      max-connections: 10

jwt:
  secret: ${JWT_KEY}