spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: discovery-service
  server:
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    com.netflix.eureka: OFF
    org.springframework.cloud.netflix.eureka: OFF
